---
- hosts: web
  tasks:
  - name: add tomcat service
    copy: src=tomcat dest=/etc/init.d/tomcat

  - name: chmod X
    file: dest=/etc/init.d/tomcat mode=755 owner=root

  - name: delete front
    shell: rm -rf /data/app/*
  - name: copy front
    copy: src=./dist/ dest=/data/app/

  - name: delete core
    shell: rm -rf /usr/local/tomcat/webapps/ROOT*
  - name: copy core
    copy: src=./brightness-core/build/libs/brightness-core-1.0.war dest=/usr/local/tomcat/webapps/ROOT.war

  - name: copy eve
    copy: src=./brightness-mongo-service/ dest=/opt/eve/

  - name: restart eve
    supervisorctl: name=eve state=restarted

  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart tomcat
    service: name=tomcat state=restarted
