export default {
  ROLE_CSR_LEAD: 'ROLE_CSR_LEAD',
  ROLE_CSR: 'ROLE_CSR',
  ROLE_FINANCIER: 'ROLE_FINANCIER',
  ROLE_LEAD: 'ROLE_LEAD',
  ROLE_VOLUNTEER: 'ROLE_VOLUNTEER',
  ROLE_ADMIN: 'ROLE_ADMIN'
}

